# Generated by Django 3.2.8 on 2021-10-27 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name="ID MLB de l'équipe")),
                ('name', models.CharField(max_length=255, verbose_name="Nom complet de l'équipe")),
                ('team_name', models.CharField(max_length=255, verbose_name="Nom court de l'équipe")),
                ('location_name', models.CharField(max_length=255, verbose_name="Localisation de l'équipe")),
                ('abbreviation', models.CharField(max_length=255, verbose_name="Acronyme de l'équipe")),
                ('link', models.CharField(max_length=255, verbose_name="Route de l'équipe dans l'API MLB")),
                ('team_code', models.IntegerField(verbose_name="Team Code de l'équipe")),
                ('team_league', models.CharField(max_length=255, verbose_name="League de l'équipe")),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_pk', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID du match')),
                ('official_date', models.DateField(verbose_name='Date du match')),
                ('home_score', models.IntegerField(verbose_name="Score de l'équipe à domicile")),
                ('away_score', models.IntegerField(verbose_name="Score de l'équipe à l'éxtérieur")),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='mlb.team', verbose_name="Equipe à l'extérieur")),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='mlb.team', verbose_name='Equipe à domicile')),
                ('winner_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_team', to='mlb.team', verbose_name='Vainqueur du match')),
            ],
        ),
    ]
