# Generated by Django 3.2.8 on 2021-11-02 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_team', to='mlb.team', verbose_name='Vainqueur du match'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(max_length=255, verbose_name="Team Code de l'équipe"),
        ),
    ]
